version: '3'

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - mkdir -p build
      - go build -o build/server server/cmd/main.go 

  run:
    deps:
      - build
    cmds:
      - ./build/server

  clean:
    cmds:
     - rm -rf build/