version: '3'

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - mkdir -p build
      - go build -o build/server server/cmd/main.go 
      - task: build-webpage
  
  build-webpage:
    dir: frontend
    cmds:
      - npm run build
      - npm run package

  run:
    dir: build/
    deps:
      - build
    cmds:
      - ./server

  clean:
    cmds:
      - rm -rf build/

  pgconnect:
    cmds:
      - psql postgresql://postgres:postgres@127.0.0.1:54322/postgres